const state = {
  view: 'list',
  docs: [],
  cwd: '',
  home: '',
  now: 0,
  filter: '',
  heavyOnly: false,
  pick: null,
  current: null,
  lastDoc: null,
  raw: '',
  text: '',
  status: '',
  error: '',
  selected: [],
  showDone: false,
  showDecisions: false,
  decisionOpen: '',
  decisionTexts: {},
  isOpen: false,
  changedAt: '',
  stop: null,
  diagrams: {},
  confirm: null,
  handoffNext: '',
  saving: false,
  alsoHandoff: false,
  handoffFromBand: false,
  pendingHandoff: null,
  disabled: false,
  reopen: null,
  handoff: null,
  olderCount: 0,
  ownHandoff: '',
  dismissed: '',
}

let queue = []
let busy = false
