const state = {
  view: 'list',
  docs: [],
  cwd: '',
  home: '',
  now: 0,
  filter: '',
  heavyOnly: false,
  collapsed: {},
  pick: null,
  current: null,
  lastDoc: null,
  raw: '',
  text: '',
  status: '',
  error: '',
  selected: [],
  showDone: false,
  showDecisions: false,
  decisionOpen: '',
  decisionTexts: {},
  isOpen: false,
  changedAt: '',
  stop: null,
  diagrams: {},
  confirm: null,
  handoffNext: '',
  saving: false,
  alsoHandoff: false,
  handoffFromBand: false,
  pendingHandoff: null,
  disabled: false,
  reopen: null,
  handoff: null,
  olderCount: 0,
  ownHandoff: '',
  dismissed: '',
  changes: { repo: '', entries: [], hasHead: false, error: '', raw: '', loaded: false },
  changeCount: 0,
  changesCollapsed: {},
  changeFile: null,
  changeDiff: null,
  diffBack: 'changes',
  allDiffs: {},
  allOpen: {},
  allLoaded: false,
  allTooMany: false,
  diffGen: 0,
  allTotal: 0,
  allFull: {},
  diffSectionClosed: {},
  images: [],
  imageAt: 0,
  changeFocus: '',
  wide: false,
  discard: null,
}

let queue = []
let busy = false
